apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spring-petclinic-08oq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-petclinic-08oq
    app.kubernetes.io/part-of: petclinic
  name: spring-petclinic-08oq
  namespace: burrsitis-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: spring-petclinic-08oq
    weight: null
status: {}
